name: debound
description: "Weather & News Dashboard App - Flutter Developer Intern Assignment"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI Dependencies
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^5.0.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.18.1
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  skeletonizer: ^1.4.3
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/core/constants/Poppins-Regular.ttf
          weight: 400
        